# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: scoring_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.12

- pip:
  # Required packages for AzureML execution, history, and data preparation.
  - azureml-defaults
  - inference-schema[numpy-support]
- scikit-learn=0.21.2
- joblib=0.13.2
- numpy=1.19.2
- pandas=1.1.3
- matplotlib=3.3.2
- seaborn=0.9.0
- scipy==1.5.4
- pytest==6.1.2
- pytest-cov==2.10.1
- install inference-schema[numpy-support]==1.2.1
- lightgbm==3.2.1
